name: Test Workflow

on:
  push:

jobs:
  fail-on-first-attempt:
    runs-on: ubuntu-22.04
    steps:
      - name: Fail on first attempt
        env:
          ATTEMPT: ${{ github.run_attempt }}
        run: |
          test "$ATTEMPT" -gt 1

      - name: Sleep
        run: |
          sleep 120

  wait:
    permissions: read-all
    runs-on: ubuntu-22.04
    steps:
      - name: wait
        uses: kachick/wait-other-jobs@v3.4.1
        timeout-minutes: 15
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
